BlogProyecto/Controllers/EntradaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BlogProyecto.Models;
using PagedList.Mvc;
using PagedList;
using BlogProyecto.Filters;


namespace BlogProyecto.Controllers
{

    public class EntradaController : Controller
    {
        private Context db = new Context();

        //
        // GET: /Entrada/

        public ViewResult Index(int page = 1)
        {

            Blog blog = db.Blogs.Find(1);
            ViewBag.blog = blog;

            Blogger blogger = db.Bloggers.Find(1);
            ViewBag.blogger = blogger; 

            List<Entrada> model = this.db.Entradas.ToList();
            model.Reverse();

            const int pageSize = 3;
            return View(model.ToPagedList(page, pageSize));
        }

        //
        // GET: /Entrada/Details/5

        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id = 0)
        {
            Entrada entrada = db.Entradas.Find(id);
            if (entrada == null)
            {
                return HttpNotFound();
            }
            return View(entrada);
        }

        //
        // GET: /Entrada/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Entrada/Create

         [ValidateInput(false)]
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Entrada entrada)
        {
            if (ModelState.IsValid)
            {
                db.Entradas.Add(entrada);
                db.SaveChanges();
                return Redirect("/Admin");
            }

            return View(entrada);
        }

        //
        // GET: /Entrada/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id = 0)
        {
            Entrada entrada = db.Entradas.Find(id);
            if (entrada == null)
            {
                return HttpNotFound();
            }
            return View(entrada);
        }

        //
        // POST: /Entrada/Edit/5
        [ValidateInput(false)]
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(Entrada entrada)
        {
            if (ModelState.IsValid)
            {
                db.Entry(entrada).State = EntityState.Modified;
                db.SaveChanges();
                return Redirect("/Admin");
            }
            return View(entrada);
        }



        [Authorize(Roles = "Admin")]
        public ActionResult List()
        {
           

            return View(db.Entradas.ToList());
        }

        //
        // POST: /Entrada/Delete/5

        [ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Entrada entrada = db.Entradas.Find(id);
            db.Entradas.Remove(entrada);
            db.SaveChanges();
            return Redirect("/Admin");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BlogProyecto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>Blog</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        <!-- Bootstrap core CSS -->
        <link href="/content/bootstrap.css" rel="stylesheet">
        <!-- Add custom CSS here -->
        <link href="/content/blog-post.css" rel="stylesheet">
        <link href="/content/site.css" rel="stylesheet">

    </head>
    <body>

        <div class="jumbotron jumbotron-sm">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <h1 class="h1">BlogProyecto

                </h1>
            </div>
        </div>
    </div>
</div>

        <header>
            <div class="content-wrapper">
                <div class="float-right">
                    
                    <nav class="navbar navbar-inverse " role="navigation">
                        <ul id="menu" class="nav navbar-nav">
                            <li>@Html.ActionLink("Blog", "Index", "Entrada")</li>
                            <li>@Html.ActionLink("Admin", "Entradas", "Admin")</li>
                        </ul>

                        <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>

                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - BlogProyecto | Designed by Oscar Jimenez</p>
                </div>
            </div>
        </footer>
         <script src="/Scripts/jquery-1.10.2.js"></script>
        <script src="/Scripts/JavaScript.js"></script>
        <script src="/Scripts/bootstrap.js"></script>
        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>